# Generated by Django 5.2 on 2025-10-20 02:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("CounselorApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("image", models.ImageField(upload_to="banners/", verbose_name="图片")),
                ("link_url", models.URLField(blank=True, verbose_name="链接地址")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("home", "首页"),
                            ("education", "宣教页"),
                            ("consultation", "咨询页"),
                        ],
                        default="home",
                        max_length=20,
                        verbose_name="位置",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("start_date", models.DateTimeField(verbose_name="开始时间")),
                ("end_date", models.DateTimeField(verbose_name="结束时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "轮播图",
                "verbose_name_plural": "轮播图",
                "ordering": ["position", "order"],
            },
        ),
        migrations.CreateModel(
            name="EducationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="栏目名称")),
                ("description", models.TextField(blank=True, verbose_name="栏目描述")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "宣教栏目",
                "verbose_name_plural": "宣教栏目",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "系统通知"),
                            ("education", "宣教通知"),
                            ("event", "活动通知"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("closed", "已关闭"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "target_audience",
                    models.JSONField(default=dict, verbose_name="目标受众"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="关闭时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "通知管理",
                "verbose_name_plural": "通知管理",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="单位名称")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("hospital", "医院"),
                            ("psychology_center", "心理咨询中心"),
                            ("social_service", "社会服务机构"),
                            ("school", "学校相关部门"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="单位类型",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="联系人"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("address", models.TextField(verbose_name="地址")),
                ("description", models.TextField(blank=True, verbose_name="单位描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "转介单位",
                "verbose_name_plural": "转介单位",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女"), ("other", "其他")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(6),
                            django.core.validators.MaxValueValidator(25),
                        ],
                        verbose_name="年龄",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                ("school", models.CharField(max_length=200, verbose_name="学校")),
                ("grade", models.CharField(max_length=50, verbose_name="年级")),
                ("class_name", models.CharField(max_length=50, verbose_name="班级")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="紧急联系人"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="紧急联系电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "学生信息",
                "verbose_name_plural": "学生信息",
                "ordering": ["school", "grade", "class_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, unique=True, verbose_name="订单号"),
                ),
                ("keywords", models.JSONField(default=list, verbose_name="咨询关键词")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="支付金额",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="CounselorApp.consultation",
                        verbose_name="咨询会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询订单",
                "verbose_name_plural": "咨询订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EducationContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "文章"),
                            ("video", "视频"),
                            ("audio", "音频"),
                            ("image", "图片"),
                        ],
                        max_length=20,
                        verbose_name="内容类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="education/thumbnails/",
                        verbose_name="缩略图",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="education/attachments/",
                        verbose_name="附件",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览数"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="CounselorAdmin.educationcategory",
                        verbose_name="栏目",
                    ),
                ),
            ],
            options={
                "verbose_name": "宣教内容",
                "verbose_name_plural": "宣教内容",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="转介原因")),
                ("referral_date", models.DateTimeField(verbose_name="转介时间")),
                (
                    "follow_up_notes",
                    models.TextField(blank=True, verbose_name="跟进记录"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "referral_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CounselorAdmin.referralunit",
                        verbose_name="转介单位",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="CounselorAdmin.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "转介记录",
                "verbose_name_plural": "转介记录",
                "ordering": ["-referral_date"],
            },
        ),
        migrations.CreateModel(
            name="NegativeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("academic", "学业问题"),
                            ("emotional", "情绪问题"),
                            ("behavioral", "行为问题"),
                            ("social", "社交问题"),
                            ("family", "家庭问题"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "轻度"),
                            ("moderate", "中度"),
                            ("severe", "重度"),
                        ],
                        max_length=20,
                        verbose_name="严重程度",
                    ),
                ),
                ("description", models.TextField(verbose_name="事件描述")),
                ("occurred_at", models.DateTimeField(verbose_name="发生时间")),
                (
                    "reported_by",
                    models.CharField(max_length=100, verbose_name="报告人"),
                ),
                (
                    "follow_up_actions",
                    models.TextField(blank=True, verbose_name="跟进措施"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="是否解决"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_events",
                        to="CounselorAdmin.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "负面事件",
                "verbose_name_plural": "负面事件",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_date", models.DateTimeField(verbose_name="访谈时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开始"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "assessment_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "危急"),
                        ],
                        max_length=20,
                        verbose_name="评估等级",
                    ),
                ),
                (
                    "interview_notes",
                    models.TextField(blank=True, verbose_name="访谈记录"),
                ),
                (
                    "follow_up_plan",
                    models.TextField(blank=True, verbose_name="后续计划"),
                ),
                (
                    "is_manual_end",
                    models.BooleanField(default=False, verbose_name="手动结束"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="CounselorApp.counselor",
                        verbose_name="咨询师",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="CounselorAdmin.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "访谈记录",
                "verbose_name_plural": "访谈记录",
                "ordering": ["-interview_date"],
            },
        ),
        migrations.CreateModel(
            name="CounselorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="排班日期")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="停诊原因"
                    ),
                ),
                (
                    "max_appointments",
                    models.PositiveIntegerField(default=5, verbose_name="最大预约数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_schedules",
                        to="CounselorApp.counselor",
                        verbose_name="咨询师",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询师排班",
                "verbose_name_plural": "咨询师排班",
                "ordering": ["date", "start_time"],
                "unique_together": {("counselor", "date", "start_time")},
            },
        ),
    ]
