# Generated by Django 5.2 on 2025-11-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("CounselorAdmin", "0004_alter_appointment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                (
                    "record_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="档案编号"
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=50, verbose_name="来访者姓名"),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("student", "student"), ("adult", "adult")],
                        default="student",
                        max_length=10,
                        verbose_name="来访者类型",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女")],
                        max_length=2,
                        verbose_name="性别",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="年龄"),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="学籍号(学生类型)",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="学校"
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="年级"
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="班级"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="教育程度(成人类型)",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="职业(成人类型)",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="紧急联系人姓名",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="紧急联系人电话",
                    ),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="咨询来源"
                    ),
                ),
                (
                    "main_complaint",
                    models.TextField(blank=True, null=True, verbose_name="主诉问题"),
                ),
                (
                    "consultation_goal",
                    models.TextField(blank=True, null=True, verbose_name="咨询目标"),
                ),
                (
                    "interview_count",
                    models.IntegerField(default=0, verbose_name="总访谈次数"),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("completed", "completed"),
                            ("closed", "closed"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="档案状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_records",
                        to="CounselorAdmin.counselor",
                        verbose_name="负责咨询师",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_consultation_records",
                        to="CounselorAdmin.counselor",
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询档案",
                "verbose_name_plural": "咨询档案",
                "db_table": "consultation_records",
            },
        ),
        migrations.CreateModel(
            name="ConsultationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[("online", "online"), ("offline", "offline")],
                        max_length=10,
                        verbose_name="服务类型",
                    ),
                ),
                (
                    "counseling_keywords",
                    models.JSONField(
                        blank=True, null=True, verbose_name="咨询关键词数组"
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="预约日期")),
                ("time_slot", models.CharField(max_length=50, verbose_name="预约时段")),
                (
                    "contact_info",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "accept_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="接单时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="CounselorAdmin.counselor",
                        verbose_name="咨询师",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="Consultant.consultationrecord",
                        verbose_name="关联档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询订单",
                "verbose_name_plural": "咨询订单",
                "db_table": "consultation_orders",
            },
        ),
        migrations.CreateModel(
            name="ConsultationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="评分(1-5)")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="评价内容"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="CounselorAdmin.counselor",
                        verbose_name="咨询师",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="Consultant.consultationorder",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询评价",
                "verbose_name_plural": "咨询评价",
                "db_table": "consultation_reviews",
            },
        ),
        migrations.CreateModel(
            name="CounselorAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("sick_leave", "sick_leave"),
                            ("personal_leave", "personal_leave"),
                            ("other", "other"),
                        ],
                        default="personal_leave",
                        max_length=20,
                        verbose_name="停诊类型",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="停诊原因"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("approved", "approved")],
                        default="pending",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="CounselorAdmin.counselor",
                        verbose_name="咨询师",
                    ),
                ),
            ],
            options={
                "verbose_name": "停诊记录",
                "verbose_name_plural": "停诊记录",
                "db_table": "counselor_absences",
            },
        ),
        migrations.CreateModel(
            name="CounselorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="真实姓名")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所属机构"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, null=True, verbose_name="个人介绍"),
                ),
                (
                    "experience",
                    models.TextField(blank=True, null=True, verbose_name="从业经验"),
                ),
                (
                    "expertise",
                    models.JSONField(
                        blank=True, null=True, verbose_name="擅长领域数组"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="教育背景"
                    ),
                ),
                (
                    "certifications",
                    models.TextField(blank=True, null=True, verbose_name="资质证书"),
                ),
                (
                    "consultation_count",
                    models.IntegerField(default=0, verbose_name="咨询次数"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "counselor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="CounselorAdmin.counselor",
                        verbose_name="咨询师",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询师详情",
                "verbose_name_plural": "咨询师详情",
                "db_table": "counselor_profiles",
            },
        ),
        migrations.CreateModel(
            name="FileStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小")),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="文件类型"),
                ),
                ("module", models.CharField(max_length=50, verbose_name="所属模块")),
                (
                    "associated_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联记录ID"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to="CounselorAdmin.counselor",
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件存储",
                "verbose_name_plural": "文件存储",
                "db_table": "file_storage",
            },
        ),
        migrations.CreateModel(
            name="ConsultantAuthToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.CharField(max_length=128, unique=True, verbose_name="Token"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="CounselorAdmin.counselor",
                        verbose_name="咨询师",
                    ),
                ),
            ],
            options={
                "db_table": "consultant_auth_tokens",
                "indexes": [
                    models.Index(fields=["token"], name="consultant__token_f1b276_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsultationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("session_number", models.IntegerField(verbose_name="第几次访谈")),
                ("interview_date", models.DateField(verbose_name="访谈日期")),
                (
                    "interview_time",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="访谈时间"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="访谈时长(分钟)"
                    ),
                ),
                (
                    "visit_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "scheduled"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="scheduled",
                        max_length=10,
                        verbose_name="访谈状态",
                    ),
                ),
                (
                    "objective_description",
                    models.TextField(blank=True, null=True, verbose_name="客观描述"),
                ),
                (
                    "doctor_evaluation",
                    models.TextField(blank=True, null=True, verbose_name="医生评定"),
                ),
                (
                    "follow_up_plan",
                    models.TextField(blank=True, null=True, verbose_name="后续计划"),
                ),
                (
                    "next_visit_plan",
                    models.TextField(
                        blank=True, null=True, verbose_name="下次访谈计划"
                    ),
                ),
                (
                    "crisis_status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="危机状态"
                    ),
                ),
                (
                    "consultant_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="咨询师姓名"
                    ),
                ),
                (
                    "is_third_party_evaluation",
                    models.BooleanField(default=False, verbose_name="是否为他评"),
                ),
                (
                    "signature_image",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="签名图片URL",
                    ),
                ),
                (
                    "attach_images",
                    models.JSONField(
                        blank=True, null=True, verbose_name="附加图片URL数组"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sessions",
                        to="CounselorAdmin.counselor",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="Consultant.consultationrecord",
                        verbose_name="档案",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询访谈",
                "verbose_name_plural": "咨询访谈",
                "db_table": "consultation_sessions",
                "unique_together": {("record", "session_number")},
            },
        ),
        migrations.CreateModel(
            name="CounselorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("schedule_date", models.DateField(verbose_name="排班日期")),
                ("time_slots", models.JSONField(verbose_name="时间段数组")),
                (
                    "max_appointments",
                    models.IntegerField(default=5, verbose_name="最大预约数"),
                ),
                (
                    "available_slots",
                    models.IntegerField(default=5, verbose_name="剩余可预约数"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="CounselorAdmin.counselor",
                        verbose_name="咨询师",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询师排班",
                "verbose_name_plural": "咨询师排班",
                "db_table": "counselor_schedules",
                "unique_together": {("counselor", "schedule_date")},
            },
        ),
    ]
