# Generated by Django 5.2 on 2025-11-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Consultant", "0002_counselorprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="counselorprofile",
            name="experience",
        ),
        migrations.AddField(
            model_name="counselorprofile",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="所在地区"
            ),
        ),
        migrations.AddField(
            model_name="counselorprofile",
            name="graduated_school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="毕业学校"
            ),
        ),
        migrations.AddField(
            model_name="counselorprofile",
            name="profession",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="心理职称"
            ),
        ),
        migrations.AddField(
            model_name="counselorprofile",
            name="skilled_filed",
            field=models.TextField(blank=True, null=True, verbose_name="擅长领域"),
        ),
        migrations.AlterField(
            model_name="counselorprofile",
            name="education",
            field=models.TextField(blank=True, null=True, verbose_name="教育背景"),
        ),
        migrations.AlterField(
            model_name="counselorprofile",
            name="expertise",
            field=models.JSONField(blank=True, null=True, verbose_name="擅长标签数组"),
        ),
    ]
