# Generated by Django 5.2 on 2025-11-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Consultant", "0003_remove_counselorprofile_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="counselorprofile",
            name="experience",
            field=models.TextField(blank=True, null=True, verbose_name="从业经验"),
        ),
    ]
