# Generated by Django 5.2 on 2025-10-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounselorAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuser",
            name="id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="用户唯一ID"
            ),
        ),
    ]
