# Generated by Django 5.2 on 2025-11-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounselorAdmin", "0002_alter_adminuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="resource",
            field=models.CharField(blank=True, max_length=200, verbose_name="资源"),
        ),
        migrations.AddField(
            model_name="article",
            name="type",
            field=models.CharField(blank=True, max_length=50, verbose_name="类型"),
        ),
        migrations.AddField(
            model_name="article",
            name="video_path",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="视频文件路径"
            ),
        ),
        migrations.AddField(
            model_name="studentreferral",
            name="image_path",
            field=models.CharField(blank=True, max_length=255, verbose_name="图片路径"),
        ),
    ]
