# Generated by Django 5.2 on 2025-11-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CounselorAdmin",
            "0003_article_resource_article_type_article_video_path_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("未开始", "未开始"),
                    ("进行中", "进行中"),
                    ("已完成", "已完成"),
                ],
                default="未开始",
                max_length=10,
                verbose_name="状态",
            ),
        ),
    ]
