# Generated by Django 5.2 on 2025-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounselorAdmin", "0004_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="contact",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="联系方式"
            ),
        ),
    ]
