# Generated by Django 5.2 on 2025-11-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounselorAdmin", "0005_appointment_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="counselor",
            name="serve_type",
            field=models.JSONField(blank=True, null=True, verbose_name="咨询方式类型"),
        ),
    ]
