# Generated by Django 5.2 on 2025-11-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CounselorAdmin", "0006_counselor_serve_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellation",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="停诊原因"),
        ),
    ]
